export type ProgramCardProgram = {
  id: string;
  title: string;
  discipline: string;
  region: string;
  exactLocation?: string | null;
  startDate: string;
  endDate: string;
  durationDays: number;
  scheduleType?: string | null;
  seasonLabel?: string | null;
  priceFromRub: number | null;
  currency?: string | null;
  priceRubApprox?: number | null;
  priceRubRateDate?: string | null;
  formatType?: string | null;
  levelRequired?: string | null;
  audienceFit?: string | null;
  riskLevel?: string | null;
  organizer?: {
    displayName: string;
    verificationStatus?: string;
    reviewCount?: number;
    ratingAvg?: number | null;
    verificationBadge?: string | null;
  };
  media?: { id?: string; url: string; mediaType: string }[];
  mediaOrderPinned?: boolean;
  autoPublished?: boolean;
  sourceType?: string | null;
  sourceUrl?: string | null;
  reviewStatus?: string | null;
};
